### GHG CH Total

https://www.climatewatchdata.org/api/v1/data/historical_emissions?regions=CHE&start_year=2014

### Docs

https://www.climatewatchdata.org/data-explorer/historical-emissions?historical-emissions-data-sources=42&historical-emissions-gases=177&historical-emissions-regions=All%20Selected&historical-emissions-sectors=509&page=1

